# Generated by Django 5.1.3 on 2024-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subscription',
        ),
        migrations.AddField(
            model_name='contact',
            name='subscription',
            field=models.ManyToManyField(related_name='subscription_type', to='news.newstype'),
        ),
    ]
