# Generated by Django 5.1.3 on 2024-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_contact_email_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnews',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
